Fix "Uncaught TypeError: $.cookie is not a function"
Was being thrown on all read pages and caused VE to no longer
load properly.

Three places make use of $.cookie():
* ve.init.mw.DesktopArticleTarget.init.js
* ve.init.mw.DesktopArticleTarget.js
* ve.ui.MWEducationPopupTool.js

Presumably this worked by luck previously due to another extension
or core module depending on it and loading earlier but no more.

Change-Id: I6b00822f1d5d17add3e298cbd77f4790899aaec2